export default {
    GET_CONSENTS_REPORT: 'GET_CONSENTS_REPORT',
    GET_CONSENTS_REPORT_FULFILLED: 'GET_CONSENTS_REPORT_FULFILLED',
    GET_VEEVA_CONSENTS_REPORT: 'GET_VEEVA_CONSENTS_REPORT',
    GET_VEEVA_CONSENTS_REPORT_FULFILLED: 'GET_VEEVA_CONSENTS_REPORT_FULFILLED'
};
