export default {
    GET_CONSENT_IMPORT_JOBS: 'GET_CONSENT_IMPORT_JOBS',
    GET_CONSENT_IMPORT_JOBS_FULFILLED: 'GET_CONSENT_IMPORT_JOBS_FULFILLED',
    CANCEL_CONSENT_IMPORT_JOB: 'CANCEL_CONSENT_IMPORT_JOB',
    CANCEL_CONSENT_IMPORT_JOB_FULFILLED: 'CANCEL_CONSENT_IMPORT_JOB_FULFILLED',
    START_CONSENT_IMPORT_JOB: 'START_CONSENT_IMPORT_JOB',
    START_CONSENT_IMPORT_JOB_FULFILLED: 'START_CONSENT_IMPORT_JOB_FULFILLED'
};
