export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_FULFILLED: 'UPDATE_PROFILE_FULFILLED',
    CREATE_USER: 'CREATE_USER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_USERS: 'GET_USERS',
    GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
    GET_USERS_REJECTED: 'GET_USERS_REJECTED',
    SORT_USERS: 'SORT_USERS'
};
