export default {
    CREATE_COUNTRY_CONSENT: 'CREATE_COUNTRY_CONSENT',
    CREATE_COUNTRY_CONSENT_FULFILLED: 'CREATE_COUNTRY_CONSENT_FULFILLED',
    GET_COUNTRY_CONSENTS: 'GET_COUNTRY_CONSENTS',
    GET_COUNTRY_CONSENTS_FULFILLED: 'GET_COUNTRY_CONSENTS_FULFILLED',
    DELETE_COUNTRY_CONSENT: 'DELETE_COUNTRY_CONSENT',
    DELETE_COUNTRY_CONSENT_FULFILLED: 'DELETE_COUNTRY_CONSENT_FULFILLED',
    UPDATE_COUNTRY_CONSENT: 'UPDATE_COUNTRY_CONSENT',
    UPDATE_COUNTRY_CONSENT_FULFILLED: 'UPDATE_COUNTRY_CONSENT_FULFILLED'
};
