version: 0.2
phases:
    install:
        commands:
            - echo install step.but nothing to install..
    pre_build:
        commands:
            - echo logging in to AWS ECR....
            - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
            - REPOSITORY_URI=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${REPO_NAME}
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
            - yarn install
            # - echo seeding database start
            # - yarn seed
            # - echo seeding database end
            # - echo running unit test
            # - yarn test
            # - echo unit test completed
            # - echo running code quality test using sonarqube
            # - yarn sonarqube
            # - echo code review with sonarqube done
    build:
        commands:
            - echo build Docker image on `date`
            - docker build -t ciam:latest .
            - echo Set Docker tag to ciam service
            - docker tag ciam:latest ${REPOSITORY_URI}:latest
            - docker tag ciam:latest ${REPOSITORY_URI}:${IMAGE_TAG}
    post_build:
        commands:
            - echo build Docker image complete `date`
            - echo push latest Docker images to ECR...
            - echo Push ciam service image to ECR
            - docker push ${REPOSITORY_URI}:latest
            - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
            - echo Writing image definitions file...
            - printf '[{"name":"%s","imageUri":"%s"}]' ${REPO_NAME} ${REPOSITORY_URI}:${IMAGE_TAG} > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
