export default {
    GET_CONSENT_CATEGORY: 'GET_CONSENT_CATEGORY',
    GET_CONSENT_CATEGORY_FULFILLED: 'GET_CONSENT_CATEGORY_FULFILLED',
    GET_CONSENT_CATEGORIES: 'GET_CONSENT_CATEGORIES',
    GET_CONSENT_CATEGORIES_FULFILLED: 'GET_CONSENT_CATEGORIES_FULFILLED',
    POST_CONSENT_CATEGORY: 'POST_CONSENT_CATEGORY',
    POST_CONSENT_CATEGORY_FULFILLED: 'POST_CONSENT_CATEGORY_FULFILLED',
    PUT_CONSENT_CATEGORY: 'PUT_CONSENT_CATEGORY',
    PUT_CONSENT_CATEGORY_FULFILLED: 'PUT_CONSENT_CATEGORY_FULFILLED'
};
