export default {
    GET_HCPS: 'GET_HCPS',
    GET_HCPS_FULFILLED: 'GET_HCPS_FULFILLED',
    EDIT_HCPS: 'EDIT_HCPS',
    EDIT_HCPS_FULFILLED: 'EDIT_HCPS_FULFILLED',
    SORT_HCPS: 'SORT_HCPS',
    SORT_HCPS_FULFILLED: 'SORT_HCPS_FULFILLED'
};
