export default {
    GET_CONSENTS_REPORT: 'GET_CONSENTS_REPORT',
    GET_CONSENTS_REPORT_FULFILLED: 'GET_CONSENTS_REPORT_FULFILLED',
    GET_VEEVA_CONSENTS_REPORT: 'GET_VEEVA_CONSENTS_REPORT',
    GET_VEEVA_CONSENTS_REPORT_FULFILLED: 'GET_VEEVA_CONSENTS_REPORT_FULFILLED',
    GET_CDP_CONSENTS: 'GET_CDP_CONSENTS',
    GET_CDP_CONSENTS_FULFILLED: 'GET_CDP_CONSENTS_FULFILLED',
    CREATE_CONSENT: 'CREATE_CONSENT',
};