export default {
    GET_HCPS: 'GET_HCPS',
    GET_HCPS_FULFILLED: 'GET_HCPS_FULFILLED',
    EDIT_HCPS: 'EDIT_HCPS',
    EDIT_HCPS_FULFILLED: 'EDIT_HCPS_FULFILLED',
    SORT_HCPS: 'SORT_HCPS',
    SORT_HCPS_FULFILLED: 'SORT_HCPS_FULFILLED',
    GET_HCP_SPECIALTIES: 'GET_HCP_SPECIALTIES',
    GET_HCP_SPECIALTIES_FULFILLED: 'GET_HCP_SPECIALTIES_FULFILLED',
    GET_OKLA_HCP_DETAILS: 'GET_OKLA_HCP_DETAILS',
    GET_OKLA_HCP_DETAILS_FULFILLED: 'GET_OKLA_HCP_DETAILS_FULFILLED',
    SET_OKLA_HCP_DETAILS: 'SET_OKLA_HCP_DETAILS',
    GET_OKLA_HCO_DETAILS: 'GET_OKLA_HCO_DETAILS',
    GET_OKLA_HCO_DETAILS_FULFILLED: 'GET_OKLA_HCO_DETAILS_FULFILLED',
    SET_OKLA_HCO_DETAILS: 'SET_OKLA_HCO_DETAILS',
    GET_HCP_FILTER_SETTINGS: 'GET_HCP_FILTER_SETTINGS',
    GET_HCP_FILTER_SETTINGS_FULFILLED: 'GET_HCP_FILTER_SETTINGS_FULFILLED'
};
