export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    CREATE_USER: 'CREATE_USER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_SITE_ADMIN_LIST: 'GET_SITE_ADMIN_LIST',
    GET_SITE_ADMIN_LIST_FULFILLED: 'GET_COUNTRY_LIST_FULFILLED'
};
