export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    CREATE_USER: 'CREATE_USER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_SITE_ADMIN_LIST: 'GET_SITE_ADMIN_LIST',
    GET_SITE_ADMIN_LIST_FULFILLED: 'GET_SITE_ADMIN_LIST_FULFILLED',
    CHANGE_SITE_ADMIN_ACCOUNT_STATUS: 'CHANGE_SITE_ADMIN_ACCOUNT_STATUS',
    CHANGE_SITE_ADMIN_ACCOUNT_STATUS_FULFILLED: 'CHANGE_SITE_ADMIN_ACCOUNT_STATUS_FULFILLED',
    DELETE_SITE_ADMIN_ACCOUNT: 'DELETE_SITE_ADMIN_ACCOUNT',
    DELETE_SITE_ADMIN_ACCOUNT_FULFILLED: 'DELETE_SITE_ADMIN_ACCOUNT_FULFILLED'
};
