export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    CREATE_USER: 'CREATE_USER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_USERS: 'GET_USERS',
    GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
    DELETE_USER: 'DELETE_USER',
    DELETE_USER_FULFILLED: 'DELETE_USER_FULFILLED'
};
