export default {
    GET_CONSENT_IMPORT_JOBS: 'GET_CONSENT_IMPORT_JOBS',
    GET_CONSENT_IMPORT_JOBS_FULFILLED: 'GET_CONSENT_IMPORT_JOBS_FULFILLED',
    DELETE_CONSENT_IMPORT_JOB: 'DELETE_CONSENT_IMPORT_JOB',
    DELETE_CONSENT_IMPORT_JOB_FULFILLED: 'DELETE_CONSENT_IMPORT_JOB_FULFILLED'
};
