export default {
    GET_PARTNER_REQUESTS: 'GET_PARTNER_REQUESTS',
    GET_PARTNER_REQUESTS_FULFILLED: 'GET_PARTNER_REQUESTS_FULFILLED',
    GET_PARTNER_REQUEST: 'GET_PARTNER_REQUEST',
    GET_PARTNER_REQUEST_FULFILLED: 'GET_PARTNER_REQUEST_FULFILLED',
    POST_PARTNER_REQUEST: 'POST_PARTNER_REQUEST',
    POST_PARTNER_REQUEST_FULFILLED: 'POST_PARTNER_REQUEST_FULFILLED',
    UPDATE_PARTNER_REQUEST: 'UPDATE_PARTNER_REQUEST',
    UPDATE_PARTNER_REQUEST_FULFILLED: 'UPDATE_PARTNER_REQUEST_FULFILLED',
    DELETE_PARTNER_REQUEST: 'DELETE_PARTNER_REQUEST',
    DELETE_PARTNER_REQUEST_FULFILLED: 'DELETE_PARTNER_REQUEST_FULFILLED',
};
