export default {
    GET_PARTNER_REQUESTS: 'GET_PARTNER_REQUESTS',
    GET_PARTNER_REQUESTS_FULFILLED: 'GET_PARTNER_REQUESTS_FULFILLED',
    POST_PARTNER_REQUEST: 'POST_PARTNER_REQUEST',
    POST_PARTNER_REQUEST_FULFILLED: 'POST_PARTNER_REQUEST_FULFILLED',
};
