export default {
    GET_PARTNER: 'GET_PARTNER',
    GET_PARTNER_FULFILLED: 'GET_PARTNER_FULFILLED',
    GET_PARTNER: 'GET_PARTNER',
    GET_PARTNER_FULFILLED: 'GET_PARTNER_FULFILLED',
    GET_PARTNER_BY_ID: 'GET_PARTNER_BY_ID',
    GET_PARTNER_BY_ID_FULFILLED: 'GET_PARTNER_BY_ID_FULFILLED',
    POST_PARTNER: 'POST_REQUEST',
    POST_PARTNER_FULFILLED: 'POST_REQUEST_FULFILLED',
    UPDATE_PARTNER: 'UPDATE_PARTNER',
    UPDATE_PARTNER_FULFILLED: 'UPDATE_PARTNER_FULFILLED',
    DELETE_PARTNER: 'DELETE_PARTNER',
    DELETE_PARTNER_FULFILLED: 'DELETE_PARTNER_FULFILLED',
};
