export default {
    GET_COUNTRIES: 'GET_COUNTRIES',
    GET_COUNTRIES_FULFILLED: 'GET_COUNTRIES_FULFILLED',
    GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
    GET_ALL_COUNTRIES_FULFILLED: 'GET_ALL_COUNTRIES_FULFILLED'
};
