INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (1, 'BE', 'BEL', 'WBE', 'Belgium');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (2, 'DE', 'DEU', 'WDE', 'Germany');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (3, 'ES', 'ESP', 'WES', 'Spain');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (4, 'FR', 'FRA', 'WFR', 'France');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (5, 'GB', 'GBR', 'WUK', 'United Kingdom');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (6, 'IE', 'IRL', 'WUK', 'Ireland');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (7, 'IT', 'ITA', 'WIT', 'Italy');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (8, 'LU', 'LUX', 'WBE', 'Luxembourg');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (9, 'MC', 'MCO', 'WFR', 'Monaco');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (10, 'NL', 'NLD', 'WNL', 'Netherlands');
INSERT INTO datasync.countries (countryid, country_iso2, country_iso3, codbase, countryname) VALUES (11, 'AD', 'AND', NULL, 'Andorra');
