CREATE TABLE cdp.partner_vendors
(
    id uuid NOT NULL,
    requestor_first_name character varying(50) COLLATE pg_catalog."default",
    requestor_last_name character varying(50) COLLATE pg_catalog."default",
    purchasing_org character varying(255) COLLATE pg_catalog."default",
    company_code character varying(255) COLLATE pg_catalog."default",
    requestor_email character varying(100) COLLATE pg_catalog."default",
    procurement_contact character varying(100) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    reg_num character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address_line_1 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address_line_2 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    post_code character varying(255) COLLATE pg_catalog."default",
    telephone character varying(25) COLLATE pg_catalog."default",
    invoice_contact_name character varying(255) COLLATE pg_catalog."default",
    invoice_address_line_1 character varying(255) COLLATE pg_catalog."default",
    invoice_address_line_2 character varying(255) COLLATE pg_catalog."default",
    invoice_post_code character varying(255) COLLATE pg_catalog."default",
    invoice_email character varying(100) COLLATE pg_catalog."default",
    invoice_telephone character varying(25) COLLATE pg_catalog."default",
    commercial_contact_name character varying(255) COLLATE pg_catalog."default",
    commercial_address_line_1 character varying(255) COLLATE pg_catalog."default",
    commercial_address_line_2 character varying(255) COLLATE pg_catalog."default",
    commercial_post_code character varying(255) COLLATE pg_catalog."default",
    commercial_email character varying(100) COLLATE pg_catalog."default",
    commercial_telephone character varying(25) COLLATE pg_catalog."default",
    ordering_contact_name character varying(255) COLLATE pg_catalog."default",
    ordering_email character varying(100) COLLATE pg_catalog."default",
    ordering_telephone character varying(25) COLLATE pg_catalog."default",
    iban character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bank_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bank_account_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(5) COLLATE pg_catalog."default" NOT NULL,
    document_urls character varying(255)[] COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT partner_vendors_pkey PRIMARY KEY (id)
)
