CREATE TABLE cdp.partner_vendors
(
    id uuid NOT NULL,
    request_id uuid NOT NULL,
    requestor_first_name character varying(50) COLLATE pg_catalog."default",
    requestor_last_name character varying(50) COLLATE pg_catalog."default",
    purchasing_org character varying(255) COLLATE pg_catalog."default",
    company_code character varying(255) COLLATE pg_catalog."default",
    requestor_email character varying(100) COLLATE pg_catalog."default",
    procurement_contact character varying(100) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    registration_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    post_code character varying(255) COLLATE pg_catalog."default",
    telephone character varying(25) COLLATE pg_catalog."default",
    invoice_contact_name character varying(255) COLLATE pg_catalog."default",
    invoice_address character varying(255) COLLATE pg_catalog."default",
    invoice_city character varying(255) COLLATE pg_catalog."default",
    invoice_post_code character varying(255) COLLATE pg_catalog."default",
    invoice_email character varying(100) COLLATE pg_catalog."default",
    invoice_telephone character varying(25) COLLATE pg_catalog."default",
    commercial_contact_name character varying(255) COLLATE pg_catalog."default",
    commercial_address character varying(255) COLLATE pg_catalog."default",
    commercial_city character varying(255) COLLATE pg_catalog."default",
    commercial_post_code character varying(255) COLLATE pg_catalog."default",
    commercial_email character varying(100) COLLATE pg_catalog."default",
    commercial_telephone character varying(25) COLLATE pg_catalog."default",
    ordering_contact_name character varying(255) COLLATE pg_catalog."default",
    ordering_email character varying(100) COLLATE pg_catalog."default",
    ordering_telephone character varying(25) COLLATE pg_catalog."default",
    iban character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bank_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bank_account_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(5) COLLATE pg_catalog."default" NOT NULL,
    status cdp.enum_partner_status NOT NULL DEFAULT 'pending'::cdp.enum_partner_status,
    type cdp.enum_partner_vendors_type NOT NULL DEFAULT 'pending'::cdp.enum_partner_vendors_type,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT partner_vendors_pkey PRIMARY KEY (id)
)
