export default {
    GET_FAQ_ITEM: 'GET_FAQ_ITEM',
    GET_FAQ_ITEM_FULFILLED: 'GET_FAQ_ITEM_FULFILLED',
    GET_FAQ_ITEMS: 'GET_FAQ_ITEMS',
    GET_FAQ_ITEMS_FULFILLED: 'GET_FAQ_ITEMS_FULFILLED',
    POST_FAQ_ITEM: 'POST_FAQ_ITEM',
    POST_FAQ_ITEM_FULFILLED: 'POST_FAQ_ITEM_FULFILLED',
    PUT_FAQ_ITEM: 'PUT_FAQ_ITEM',
    PUT_FAQ_ITEM_FULFILLED: 'PUT_FAQ_ITEM_FULFILLED',
    DELETE_FAQ_ITEM: 'DELETE_FAQ_ITEM',
    DELETE_FAQ_ITEM_FULFILLED: 'DELETE_FAQ_ITEM_FULFILLED',
};
