export default {
    GET_CONSENT_PREFERENCE: 'GET_CONSENT_PREFERENCE',
    GET_CONSENT_PREFERENCE_FULFILLED: 'GET_CONSENT_PREFERENCE_FULFILLED',
    GET_CONSENT_PREFERENCES: 'GET_CONSENT_PREFERENCES',
    GET_CONSENT_PREFERENCES_FULFILLED: 'GET_CONSENT_PREFERENCES_FULFILLED',
    POST_CONSENT_PREFERENCE: 'POST_CONSENT_PREFERENCE',
    POST_CONSENT_PREFERENCE_FULFILLED: 'POST_CONSENT_PREFERENCE_FULFILLED',
    PUT_CONSENT_PREFERENCE: 'PUT_CONSENT_PREFERENCE',
    PUT_CONSENT_PREFERENCE_FULFILLED: 'PUT_CONSENT_PREFERENCE_FULFILLED'
};
