export default {
    GET_TRIAL_ITEM: 'GET_TRIAL_ITEM',
    GET_TRIAL_ITEM_FULFILLED: 'GET_TRIAL_ITEM_FULFILLED', 
    GET_TRIAL_DETAILS: 'GET_TRIAL_DETAILS',
    GET_TRIAL_DETAILS_FULFILLED: 'GET_TRIAL_DETAILS_FULFILLED'
};