export default {
    GET_TRIAL_ITEM: 'GET_TRIAL_ITEM',
    GET_TRIAL_ITEM_FULFILLED: 'GET_TRIAL_ITEM_FULFILLED', 
    GET_TRIAL_DETAILS: 'GET_TRIAL_DETAILS',
    GET_TRIAL_DETAILS_FULFILLED: 'GET_TRIAL_DETAILS_FULFILLED',
    GET_TRIAL_ITEMS: 'GET_TRIAL_ITEMS', 
    GET_TRIAL_ITEMS_FULFILLED: 'GET_TRIAL_ITEMS_FULFILLED',
    GET_TRIAL_CONDITIONS: 'GET_TRIAL_CONDITIONS',
    GET_TRIAL_CONDITIONS_FULFILLED: 'GET_TRIAL_CONDITIONS_FULFILLED'
};